### ISSUE TITLE
Arduino beeps

### ISSUE THREAD

**Issue by silvapacita** [JBoye/HACKTANE#4]
The beep (arduino 13 pin) small beeps on 1-2-3-4-5-6-7-8, but on the last 3 seconds of each 10, it long beeps (like if it was a strike).

**Comment by JBoye** [comment]
Did you use my Arduino code for your project?

**Comment by silvapacita** [comment]
I use your Arduino code from GitHub, but the only problem I had was the segments were all wrong (also use a 16 pin, 7 segment and 4 digits led)

**Comment by JBoye** [comment]
I think the issue is in the arduino code and not the mod itself. The mod doesn’t send any “beebs”, the arduino just detects changes in the timer. 
I’m not really an expert in C/Arduino, but if someone is able to fix it let me know

**Comment by silvapacita** [comment]
@JBoye isn't this yours?
https://gist.github.com/JBoye/14631e358b015ba14210
is uses beepTime < 100 and < 500 for striketime on digitalWrite(13)
But if you don't know how to fix this, don't worry about this issue, i'll make a new code corrected and post it in here. ;)

**Comment by JBoye** [comment]
It is, but it is the only arduino project i have ever made. So I'm not really sure how to fix it :)

**Comment by silvapacita** [comment]
no problem, i'll make a different one and post it :)

**Comment by silvapacita** [comment]
The user @nilsmunch just posted on GitHub an arduino code for your mod:
https://github.com/nilsmunch/KTANE-Bombtimer
Haven't tested it yet, but at first sight, everything seems ok.

**Comment by silvapacita** [comment]
[Hacktane_Silvapacita_V1_1.zip](https://github.com/JBoye/HACKTANE/files/1338411/Hacktane_Silvapacita_V1_1.zip)

For using 4 digit / 7 segment (16 pins) led display
pins 2->9 segments
pins10->13 digits
pins A0 and A1 are relays for normal and alarm light
